services:
  frontend:
    build: ./frontend
    restart: always
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
      HOST: 0.0.0.0
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - '3000:3000'
    depends_on:
      - api
    volumes:
      - /app/node_modules
      - ./frontend:/app
  api:
    build: ./api
    restart: always
    ports:
      - '5050:5050'
    volumes:
      - ./api:/app